//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFiller_APP.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDFExportData
    {
        public long Id { get; set; }
        public string UniqueId { get; set; }
        public string Source { get; set; }
        public string FilePath { get; set; }
        public string Surgeon { get; set; }
        public string Preparer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
